- hosts: localhost
  gather_facts: false
  tasks:
    - name: show active callback  (환경/설정 확인)
      command: bash -lc 'ansible-config dump | grep -E "^DEFAULT_STDOUT_CALLBACK|^DEFAULT_NO_TARGET_SYSLOG"'
      register: cfg

    - debug:
        var: cfg.stdout_lines

    - name: print success json
      debug:
        msg:
          host: "10.100.64.235"
          status: "success"
          directory: "/home/rocky"
          scan_time: "{{ lookup('pipe','date -Iseconds') }}"
          summary: { total_files: 5 }

    - name: print failed json
      debug:
        msg:
          host: "10.100.64.236"
          status: "failed"
          error: "connection_failed"
          message: "SSH 연결 실패"
          scan_time: "{{ lookup('pipe','date -Iseconds') }}"
