- hosts: localhost
  gather_facts: false
  vars:
    now: "{{ lookup('pipe','date -Iseconds') }}"
  tasks:
    # 진단용 command/grep 태스크는 제거
    - name: print success json
      debug:
        msg:
          host: "10.100.64.235"
          status: "success"
          directory: "/home/rocky"
          scan_time: "{{ now }}"
          summary: { total_files: 5 }
      changed_when: false

    - name: print failed json
      debug:
        msg:
          host: "10.100.64.236"
          status: "failed"
          error: "connection_failed"
          message: "SSH 연결 실패"
          scan_time: "{{ now }}"
      changed_when: false
