- name: print only sample logs
  hosts: localhost
  gather_facts: false
  vars:
    now: "{{ lookup('pipe','date -Iseconds') }}"
  tasks:
    - name: print success json
      debug:
        msg: |
          {
            "host": "10.100.64.235",
            "status": "success",
            "directory": "/home/rocky",
            "scan_time": "{{ now }}",
            "summary": { "total_files": 5 }
          }

    - name: print failed json
      debug:
        msg: |
          {
            "host": "10.100.64.236",
            "status": "failed",
            "error": "connection_failed",
            "message": "SSH 연결 실패",
            "scan_time": "{{ now }}"
          }
